title: Jon Kulton
email: jonkulton@gmail.com
description: >-
  Jon Kulton | Softare Engineer
baseurl: ""
url: "https://jkulton.com"
twitter_username: jkulton
github_username:  jkulton

plugins:
  - jekyll-feed
  - jekyll-postcss

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
