title: Jon Kulton
email: jonkulton@gmail.com
description: >-
  Jon Kulton | Softare Engineer
baseurl: ""
url: "https://jkulton.com"
twitter_username: jkulton
github_username: jkulton

plugins:
  - jekyll-feed
  - jekyll-postcss

sass:
  load_paths:
    - _sass
    - node_modules

include: ["node_modules/tailwindcss"]
