# Site settings
title: Jon Kulton
email: jonkulton@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Jon Kulton: Designer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jkulton.github.io" # the base hostname & protocol for your site
twitter_username: jkulton
github_username:  jkulton

# Build settings
markdown: kramdown
