name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2.5.0
      with:
       build_dir: _site/
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
